event.not.found=event not found for id: 
eventtype.not.found=event type not found for id: 
partner.not.found=partner not found for id: 
partnerrole.not.found=partner role not found for id: 
ispartner.not.found=is partner not found for id: 
email.already.exists= email already exists


app.jwt.secret=357638792F423F4428472B4B6250655368566D597133743677397A2443264629
app.jwt.expiration=86400000
